packages:
  - .
  - config/*
  - frontend
  - frontend/base
  - frontend/pro
  - frontend/antd
  - frontend/antdx

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - svelte-preprocess
